name: Run Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: 'jdk'
        architecture: 'x64'
        check-latest: false
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true
        job-status: 'success'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=${RUNNER_TOOL_CACHE}/jdk/11" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean test -Dcucumber.options="--tags @TC5"
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
